<?php
/** @var Magento\Framework\View\Element\Template $block */
/** @var Magento\Framework\Escaper $escaper */
/** @var Panda\Tag\ViewModel\Tag $tagVm */
$tagVm =$block->getData('tag_vm')
?>

<div class="tag-list">
    <h1><?= __('Tags') ?></h1>
    <ul>
        <?php foreach ($tagVm->getList() as $tag): ?>
            <li>
                <a href="<?= $block->getUrl('tag/tag/detail', ['id' => $tag->getData('id')]) ?>">
                    <?= $escaper->escapeHtml($tag->getData('name')) ?>
                </a></li>
        <?php endforeach ?>

    </ul>
    <p><?=__('Tags count: %1', $tagVm->getCount())?></p>
</div>
